### ISSUE TITLE
How Format my json from af.database.list

### ISSUE THREAD

**Issue by agumack** [angular/angularfire2#176]
Hi,

This my data firebase structure:
```
sections:
 - section1: {name: News}
 - section2: {name: Tech, parent: section 1}
 - section3: {name: Other, parent: section1}

```
Get Section list: var sections =  this.af.database.object('/sections'); => working fine
 
Now how do loop 'sections' and return a new json by my structure:
```
Ex: [
{
      name: News,
      nodes: [
          name: Tech, nodes: [] 
     ]
]
```

Because i can't using foreach(var s in sections) :(

thank you so much,
